export const PanopticVaultAccountantAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'computeNAV',
    inputs: [
      { name: 'vault', type: 'address', internalType: 'address' },
      { name: 'underlyingToken', type: 'address', internalType: 'address' },
      { name: 'managerInput', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: 'nav', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lockVault',
    inputs: [{ name: 'vault', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updatePoolsHash',
    inputs: [
      { name: 'vault', type: 'address', internalType: 'address' },
      { name: 'poolsHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'vaultLocked',
    inputs: [{ name: 'vault', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'isLocked', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vaultPools',
    inputs: [{ name: 'vault', type: 'address', internalType: 'address' }],
    outputs: [{ name: 'poolsHash', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'CastingError', inputs: [] },
  { type: 'error', name: 'IncorrectPositionList', inputs: [] },
  { type: 'error', name: 'InvalidPools', inputs: [] },
  { type: 'error', name: 'InvalidTick', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'StaleOraclePrice', inputs: [] },
  { type: 'error', name: 'UnderOverFlow', inputs: [] },
  { type: 'error', name: 'VaultLocked', inputs: [] },
] as const
