export const PanopticFactoryAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_SFPM',
        type: 'address',
        internalType: 'contract SemiFungiblePositionManager',
      },
      {
        name: '_univ3Factory',
        type: 'address',
        internalType: 'contract IUniswapV3Factory',
      },
      { name: '_poolReference', type: 'address', internalType: 'address' },
      { name: '_collateralReference', type: 'address', internalType: 'address' },
      { name: 'properties', type: 'bytes32[]', internalType: 'bytes32[]' },
      { name: 'indices', type: 'uint256[][]', internalType: 'uint256[][]' },
      { name: 'pointers', type: 'uint256[][]', internalType: 'Pointer[][]' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'constructMetadata',
    inputs: [
      { name: 'panopticPool', type: 'address', internalType: 'address' },
      { name: 'symbol0', type: 'string', internalType: 'string' },
      { name: 'symbol1', type: 'string', internalType: 'string' },
      { name: 'fee', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deployNewPool',
    inputs: [
      { name: 'token0', type: 'address', internalType: 'address' },
      { name: 'token1', type: 'address', internalType: 'address' },
      { name: 'fee', type: 'uint24', internalType: 'uint24' },
      { name: 'salt', type: 'uint96', internalType: 'uint96' },
    ],
    outputs: [{ name: 'newPoolContract', type: 'address', internalType: 'contract PanopticPool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getApproved',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPanopticPool',
    inputs: [{ name: 'univ3pool', type: 'address', internalType: 'contract IUniswapV3Pool' }],
    outputs: [{ name: '', type: 'address', internalType: 'contract PanopticPool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minePoolAddress',
    inputs: [
      { name: 'deployerAddress', type: 'address', internalType: 'address' },
      { name: 'v3Pool', type: 'address', internalType: 'address' },
      { name: 'salt', type: 'uint96', internalType: 'uint96' },
      { name: 'loops', type: 'uint256', internalType: 'uint256' },
      { name: 'minTargetRarity', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'bestSalt', type: 'uint96', internalType: 'uint96' },
      { name: 'highestRarity', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'spender', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ApprovalForAll',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PoolDeployed',
    inputs: [
      {
        name: 'poolAddress',
        type: 'address',
        indexed: true,
        internalType: 'contract PanopticPool',
      },
      {
        name: 'uniswapPool',
        type: 'address',
        indexed: true,
        internalType: 'contract IUniswapV3Pool',
      },
      {
        name: 'collateralTracker0',
        type: 'address',
        indexed: false,
        internalType: 'contract CollateralTracker',
      },
      {
        name: 'collateralTracker1',
        type: 'address',
        indexed: false,
        internalType: 'contract CollateralTracker',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'PoolAlreadyInitialized', inputs: [] },
  { type: 'error', name: 'UniswapPoolNotInitialized', inputs: [] },
] as const
