import { SemiFungiblePositionManagerAbi as SFPMAbi } from './SemiFungiblePositionManager'

const panopticPoolAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_sfpm',
        type: 'address',
        internalType: 'contract SemiFungiblePositionManager',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'assertMinCollateralValues',
    inputs: [
      { name: 'minValue0', type: 'uint256', internalType: 'uint256' },
      { name: 'minValue1', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'burnOptions',
    inputs: [
      { name: 'tokenId', type: 'uint256', internalType: 'TokenId' },
      { name: 'newPositionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'tickLimitLow', type: 'int24', internalType: 'int24' },
      { name: 'tickLimitHigh', type: 'int24', internalType: 'int24' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burnOptions',
    inputs: [
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'newPositionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'tickLimitLow', type: 'int24', internalType: 'int24' },
      { name: 'tickLimitHigh', type: 'int24', internalType: 'int24' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collateralToken0',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract CollateralTracker' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'collateralToken1',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract CollateralTracker' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'forceExercise',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'TokenId' },
      { name: 'positionIdListExercisee', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'positionIdListExercisor', type: 'uint256[]', internalType: 'TokenId[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getAccumulatedFeesAndPositionsData',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'includePendingPremium', type: 'bool', internalType: 'bool' },
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
    ],
    outputs: [
      { name: '', type: 'uint256', internalType: 'LeftRightUnsigned' },
      { name: '', type: 'uint256', internalType: 'LeftRightUnsigned' },
      { name: '', type: 'uint256[2][]', internalType: 'uint256[2][]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOracleTicks',
    inputs: [],
    outputs: [
      { name: 'currentTick', type: 'int24', internalType: 'int24' },
      { name: 'fastOracleTick', type: 'int24', internalType: 'int24' },
      { name: 'slowOracleTick', type: 'int24', internalType: 'int24' },
      { name: 'latestObservation', type: 'int24', internalType: 'int24' },
      { name: 'medianData', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isSafeMode',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'liquidate',
    inputs: [
      { name: 'positionIdListLiquidator', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'liquidatee', type: 'address', internalType: 'address' },
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mintOptions',
    inputs: [
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'positionSize', type: 'uint128', internalType: 'uint128' },
      { name: 'effectiveLiquidityLimitX32', type: 'uint64', internalType: 'uint64' },
      { name: 'tickLimitLow', type: 'int24', internalType: 'int24' },
      { name: 'tickLimitHigh', type: 'int24', internalType: 'int24' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'numberOfPositions',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'onERC1155BatchReceived',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155Received',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pokeMedian',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'positionData',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'TokenId' },
    ],
    outputs: [
      { name: '', type: 'int24', internalType: 'int24' },
      { name: '', type: 'int24', internalType: 'int24' },
      { name: '', type: 'int24', internalType: 'int24' },
      { name: '', type: 'int24', internalType: 'int24' },
      { name: '', type: 'int256', internalType: 'int256' },
      { name: '', type: 'int256', internalType: 'int256' },
      { name: '', type: 'uint128', internalType: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'settleLongPremium',
    inputs: [
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'legIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collectPremium',
    inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'TokenId' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'startPool',
    inputs: [
      { name: '_univ3pool', type: 'address', internalType: 'contract IUniswapV3Pool' },
      { name: 'token0', type: 'address', internalType: 'address' },
      { name: 'token1', type: 'address', internalType: 'address' },
      {
        name: 'collateralTracker0',
        type: 'address',
        internalType: 'contract CollateralTracker',
      },
      {
        name: 'collateralTracker1',
        type: 'address',
        internalType: 'contract CollateralTracker',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'univ3pool',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IUniswapV3Pool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'validateCollateralWithdrawable',
    inputs: [
      { name: 'user', type: 'address', internalType: 'address' },
      { name: 'positionIdList', type: 'uint256[]', internalType: 'TokenId[]' },
    ],
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'AccountLiquidated',
    inputs: [
      { name: 'liquidator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'liquidatee', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'bonusAmounts',
        type: 'int256',
        indexed: false,
        internalType: 'LeftRightSigned',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ForcedExercised',
    inputs: [
      { name: 'exercisor', type: 'address', indexed: true, internalType: 'address' },
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      {
        name: 'exerciseFee',
        type: 'int256',
        indexed: false,
        internalType: 'LeftRightSigned',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OptionBurnt',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'positionSize', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      {
        name: 'premiaByLeg',
        type: 'int256[4]',
        indexed: false,
        internalType: 'LeftRightSigned[4]',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OptionMinted',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      {
        name: 'balanceData',
        type: 'uint256',
        indexed: false,
        internalType: 'PositionBalance',
      },
      {
        name: 'commissions',
        type: 'uint256',
        indexed: false,
        internalType: 'LeftRightUnsigned',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PremiumSettled',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      { name: 'legIndex', type: 'uint256', indexed: false, internalType: 'uint256' },
      {
        name: 'settledAmounts',
        type: 'int256',
        indexed: false,
        internalType: 'LeftRightSigned',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AccountInsolvent', inputs: [] },
  { type: 'error', name: 'CastingError', inputs: [] },
  { type: 'error', name: 'EffectiveLiquidityAboveThreshold', inputs: [] },
  { type: 'error', name: 'InputListFail', inputs: [] },
  { type: 'error', name: 'InvalidTick', inputs: [] },
  {
    type: 'error',
    name: 'InvalidTokenIdParameter',
    inputs: [{ name: 'parameterType', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'NoLegsExercisable', inputs: [] },
  { type: 'error', name: 'NotALongLeg', inputs: [] },
  { type: 'error', name: 'NotMarginCalled', inputs: [] },
  { type: 'error', name: 'PoolAlreadyInitialized', inputs: [] },
  { type: 'error', name: 'PositionAlreadyMinted', inputs: [] },
  { type: 'error', name: 'StaleTWAP', inputs: [] },
  { type: 'error', name: 'TooManyPositionsOpen', inputs: [] },
  { type: 'error', name: 'UnderOverFlow', inputs: [] },
] as const

// Add sfpm errors to PanopticPoolABI so error types can be inferred using the (`walk` method) when PanopticPool call reverts with a custom error defined in the SFPM.
export const PanopticPoolAbi = [
  ...panopticPoolAbi,
  ...SFPMAbi.filter((abiEntry) => abiEntry.type === 'error'),
] as const
