//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// BuilderFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const builderFactoryAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'OWNER',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'builderCode', internalType: 'uint48', type: 'uint48' },
      { name: 'builderAdmin', internalType: 'address', type: 'address' },
    ],
    name: 'deployBuilder',
    outputs: [{ name: 'wallet', internalType: 'address', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'builderCode', internalType: 'uint48', type: 'uint48' }],
    name: 'predictBuilderWallet',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'builderCode',
        internalType: 'uint48',
        type: 'uint48',
        indexed: true,
      },
      {
        name: 'wallet',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'builderAdmin',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'BuilderWalletDeployed',
  },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// BuilderWallet
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const builderWalletAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'factory', internalType: 'address', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FACTORY',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'builderAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_builderAdmin', internalType: 'address', type: 'address' }],
    name: 'init',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
    ],
    name: 'sweep',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'builderAdmin',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'BuilderWalletInitialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'TokensSwept',
  },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'NotBuilder' },
  {
    type: 'error',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'balance', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'TransferFailed',
  },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// CollateralTracker
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const collateralTrackerAbi = [
  {
    type: 'constructor',
    inputs: [{ name: '_commissionFee', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'accrueInterest',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: 'allowance', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'asset',
    outputs: [{ name: 'assetTokenAddress', internalType: 'address', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'assetsAndInterest',
    outputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'assetsOf',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: 'balance', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'borrowIndex',
    outputs: [{ name: '', internalType: 'uint80', type: 'uint80' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    name: 'convertToAssets',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    name: 'convertToShares',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'delegatee', internalType: 'address', type: 'address' }],
    name: 'delegate',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'assets', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'address', type: 'address' },
    ],
    name: 'deposit',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getPoolData',
    outputs: [
      { name: 'depositedAssets', internalType: 'uint256', type: 'uint256' },
      { name: 'insideAMM', internalType: 'uint256', type: 'uint256' },
      { name: 'creditedShares', internalType: 'uint256', type: 'uint256' },
      {
        name: 'currentPoolUtilization',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'interestRate',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'interestState',
    outputs: [
      { name: 'userBorrowIndex', internalType: 'int128', type: 'int128' },
      { name: 'netBorrows', internalType: 'int128', type: 'int128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lastInteractionTimestamp',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'maxDeposit',
    outputs: [{ name: 'maxAssets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'maxMint',
    outputs: [{ name: 'maxShares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'maxRedeem',
    outputs: [{ name: 'maxShares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'maxWithdraw',
    outputs: [{ name: 'maxAssets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'shares', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'address', type: 'address' },
    ],
    name: 'mint',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes[]', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', internalType: 'bytes[]', type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'owedInterest',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'panopticPool',
    outputs: [{ name: '', internalType: 'contract PanopticPool', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poolFee',
    outputs: [{ name: '_poolFee', internalType: 'uint24', type: 'uint24' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poolManager',
    outputs: [{ name: '', internalType: 'contract IPoolManager', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    name: 'previewDeposit',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    name: 'previewMint',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'previewOwedInterest',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    name: 'previewRedeem',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    name: 'previewWithdraw',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'rateAtTarget',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'shares', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'address', type: 'address' },
      { name: 'owner', internalType: 'address', type: 'address' },
    ],
    name: 'redeem',
    outputs: [{ name: 'assets', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'reentrancyGuardEntered',
    outputs: [{ name: 'entered', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'refunder', internalType: 'address', type: 'address' },
      { name: 'refundee', internalType: 'address', type: 'address' },
      { name: 'assets', internalType: 'int256', type: 'int256' },
    ],
    name: 'refund',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'delegatee', internalType: 'address', type: 'address' }],
    name: 'revoke',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'riskEngine',
    outputs: [{ name: '', internalType: 'contract IRiskEngine', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'optionOwner', internalType: 'address', type: 'address' },
      { name: 'longAmount', internalType: 'int128', type: 'int128' },
      { name: 'shortAmount', internalType: 'int128', type: 'int128' },
      { name: 'ammDeltaAmount', internalType: 'int128', type: 'int128' },
      { name: 'realizedPremium', internalType: 'int128', type: 'int128' },
      {
        name: 'riskParameters',
        internalType: 'RiskParameters',
        type: 'uint256',
      },
    ],
    name: 'settleBurn',
    outputs: [{ name: '', internalType: 'int128', type: 'int128' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'liquidator', internalType: 'address', type: 'address' },
      { name: 'liquidatee', internalType: 'address', type: 'address' },
      { name: 'bonus', internalType: 'int256', type: 'int256' },
    ],
    name: 'settleLiquidation',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'optionOwner', internalType: 'address', type: 'address' },
      { name: 'longAmount', internalType: 'int128', type: 'int128' },
      { name: 'shortAmount', internalType: 'int128', type: 'int128' },
      { name: 'ammDeltaAmount', internalType: 'int128', type: 'int128' },
      {
        name: 'riskParameters',
        internalType: 'RiskParameters',
        type: 'uint256',
      },
    ],
    name: 'settleMint',
    outputs: [
      { name: '', internalType: 'uint32', type: 'uint32' },
      { name: '', internalType: 'int128', type: 'int128' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'token0',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'token1',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalAssets',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'recipient', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'underlyingIsToken0',
    outputs: [{ name: '_underlyingIsToken0', internalType: 'bool', type: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'underlyingToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes', type: 'bytes' }],
    name: 'unlockCallback',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unrealizedGlobalInterest',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'assets', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'address', type: 'address' },
      { name: 'owner', internalType: 'address', type: 'address' },
    ],
    name: 'withdraw',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'assets', internalType: 'uint256', type: 'uint256' },
      { name: 'receiver', internalType: 'address', type: 'address' },
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      { name: 'usePremiaAsCollateral', internalType: 'bool', type: 'bool' },
    ],
    name: 'withdraw',
    outputs: [{ name: 'shares', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'builder',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'commissionPaidProtocol',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'commissionPaidBuilder',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'CommissionPaid',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'assets',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'shares',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Deposit',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'interestOwed',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'interestPaid',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'sharesBurned',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'InsolvencyPenaltyApplied',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'liquidatee',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'liquidator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'protocolLossAssets',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'protocolLossShares',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ProtocolLossRealized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'receiver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'assets',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'shares',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Withdraw',
  },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'BelowMinimumRedemption' },
  { type: 'error', inputs: [], name: 'CastingError' },
  { type: 'error', inputs: [], name: 'DepositTooLarge' },
  { type: 'error', inputs: [], name: 'ExceedsMaximumRedemption' },
  {
    type: 'error',
    inputs: [
      { name: 'tokenAddress', internalType: 'address', type: 'address' },
      { name: 'assetsRequested', internalType: 'uint256', type: 'uint256' },
      { name: 'assetBalance', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'NotEnoughTokens',
  },
  { type: 'error', inputs: [], name: 'NotPanopticPool' },
  { type: 'error', inputs: [], name: 'PositionCountNotZero' },
  { type: 'error', inputs: [], name: 'Reentrancy' },
  {
    type: 'error',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'balance', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'TransferFailed',
  },
  { type: 'error', inputs: [], name: 'UnauthorizedUniswapCallback' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PanopticFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const panopticFactoryAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_SFPM',
        internalType: 'contract SemiFungiblePositionManager',
        type: 'address',
      },
      {
        name: '_manager',
        internalType: 'contract IPoolManager',
        type: 'address',
      },
      { name: '_poolReference', internalType: 'address', type: 'address' },
      {
        name: '_collateralReference',
        internalType: 'address',
        type: 'address',
      },
      { name: 'properties', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'indices', internalType: 'uint256[][]', type: 'uint256[][]' },
      { name: 'pointers', internalType: 'Pointer[][]', type: 'uint256[][]' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'panopticPool', internalType: 'address', type: 'address' },
      { name: 'symbol0', internalType: 'string', type: 'string' },
      { name: 'symbol1', internalType: 'string', type: 'string' },
      { name: 'fee', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'constructMetadata',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'key',
        internalType: 'struct PoolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', internalType: 'Currency', type: 'address' },
          { name: 'currency1', internalType: 'Currency', type: 'address' },
          { name: 'fee', internalType: 'uint24', type: 'uint24' },
          { name: 'tickSpacing', internalType: 'int24', type: 'int24' },
          { name: 'hooks', internalType: 'contract IHooks', type: 'address' },
        ],
      },
      {
        name: 'riskEngine',
        internalType: 'contract IRiskEngine',
        type: 'address',
      },
      { name: 'salt', internalType: 'uint96', type: 'uint96' },
    ],
    name: 'deployNewPool',
    outputs: [
      {
        name: 'newPoolContract',
        internalType: 'contract PanopticPool',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'keyV4',
        internalType: 'struct PoolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', internalType: 'Currency', type: 'address' },
          { name: 'currency1', internalType: 'Currency', type: 'address' },
          { name: 'fee', internalType: 'uint24', type: 'uint24' },
          { name: 'tickSpacing', internalType: 'int24', type: 'int24' },
          { name: 'hooks', internalType: 'contract IHooks', type: 'address' },
        ],
      },
      {
        name: 'riskEngine',
        internalType: 'contract IRiskEngine',
        type: 'address',
      },
    ],
    name: 'getPanopticPool',
    outputs: [{ name: '', internalType: 'contract PanopticPool', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'deployerAddress', internalType: 'address', type: 'address' },
      {
        name: 'key',
        internalType: 'struct PoolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', internalType: 'Currency', type: 'address' },
          { name: 'currency1', internalType: 'Currency', type: 'address' },
          { name: 'fee', internalType: 'uint24', type: 'uint24' },
          { name: 'tickSpacing', internalType: 'int24', type: 'int24' },
          { name: 'hooks', internalType: 'contract IHooks', type: 'address' },
        ],
      },
      { name: 'riskEngine', internalType: 'address', type: 'address' },
      { name: 'salt', internalType: 'uint96', type: 'uint96' },
      { name: 'loops', internalType: 'uint256', type: 'uint256' },
      { name: 'minTargetRarity', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'minePoolAddress',
    outputs: [
      { name: 'bestSalt', internalType: 'uint96', type: 'uint96' },
      { name: 'highestRarity', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes[]', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', internalType: 'bytes[]', type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address' },
      { name: 'approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'id', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'poolAddress',
        internalType: 'contract PanopticPool',
        type: 'address',
        indexed: true,
      },
      { name: 'idV4', internalType: 'PoolId', type: 'bytes32', indexed: true },
      {
        name: 'collateralTracker0',
        internalType: 'contract CollateralTracker',
        type: 'address',
        indexed: false,
      },
      {
        name: 'collateralTracker1',
        internalType: 'contract CollateralTracker',
        type: 'address',
        indexed: false,
      },
      {
        name: 'riskEngine',
        internalType: 'contract IRiskEngine',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'PoolDeployed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
    ],
    name: 'Transfer',
  },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'CreateFail' },
  { type: 'error', inputs: [], name: 'PoolNotInitialized' },
  { type: 'error', inputs: [], name: 'ZeroAddress' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PanopticHelper
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const panopticHelperAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_SFPM',
        internalType: 'contract ISemiFungiblePositionManager',
        type: 'address',
      },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'pool', internalType: 'contract PanopticPool', type: 'address' },
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
    ],
    name: 'checkCollateral',
    outputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'univ3pool',
        internalType: 'contract IUniswapV3Pool',
        type: 'address',
      },
      { name: 'cardinality', internalType: 'uint256', type: 'uint256' },
      { name: 'period', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'computeMedianObservedPrice',
    outputs: [{ name: '', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'pool', internalType: 'address', type: 'address' },
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
    ],
    name: 'findLiquidationPriceDown',
    outputs: [{ name: 'liquidationTick', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'pool', internalType: 'address', type: 'address' },
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
    ],
    name: 'findLiquidationPriceUp',
    outputs: [{ name: 'liquidationTick', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'pool', internalType: 'contract PanopticPool', type: 'address' },
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
    ],
    name: 'getPortfolioValue',
    outputs: [
      { name: 'value0', internalType: 'int256', type: 'int256' },
      { name: 'value1', internalType: 'int256', type: 'int256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'pool', internalType: 'contract PanopticPool', type: 'address' },
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'TokenId', type: 'uint256' },
    ],
    name: 'optionPositionInfo',
    outputs: [
      { name: '', internalType: 'uint128', type: 'uint128' },
      { name: '', internalType: 'uint16', type: 'uint16' },
      { name: '', internalType: 'uint16', type: 'uint16' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'univ3pool',
        internalType: 'contract IUniswapV3Pool',
        type: 'address',
      },
      { name: 'twapWindow', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'twapFilter',
    outputs: [{ name: '', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  { type: 'error', inputs: [], name: 'InvalidTick' },
  { type: 'error', inputs: [], name: 'LiquidityTooHigh' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PanopticPool
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const panopticPoolAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_sfpm',
        internalType: 'contract ISemiFungiblePositionManager',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'SFPM',
    outputs: [
      {
        name: '',
        internalType: 'contract ISemiFungiblePositionManager',
        type: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'minValue0', internalType: 'uint256', type: 'uint256' },
      { name: 'minValue1', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'assertMinCollateralValues',
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'collateralToken0',
    outputs: [{ name: '', internalType: 'contract CollateralTracker', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'collateralToken1',
    outputs: [{ name: '', internalType: 'contract CollateralTracker', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      {
        name: 'finalPositionIdList',
        internalType: 'TokenId[]',
        type: 'uint256[]',
      },
      { name: 'positionSizes', internalType: 'uint128[]', type: 'uint128[]' },
      {
        name: 'tickAndSpreadLimits',
        internalType: 'int24[3][]',
        type: 'int24[3][]',
      },
      { name: 'usePremiaAsCollateral', internalType: 'bool', type: 'bool' },
      { name: 'builderCode', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'dispatch',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'positionIdListFrom',
        internalType: 'TokenId[]',
        type: 'uint256[]',
      },
      { name: 'account', internalType: 'address', type: 'address' },
      {
        name: 'positionIdListTo',
        internalType: 'TokenId[]',
        type: 'uint256[]',
      },
      {
        name: 'positionIdListToFinal',
        internalType: 'TokenId[]',
        type: 'uint256[]',
      },
      {
        name: 'usePremiaAsCollateral',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
    ],
    name: 'dispatchFrom',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'includePendingPremium', internalType: 'bool', type: 'bool' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
    ],
    name: 'getAccumulatedFeesAndPositionsData',
    outputs: [
      { name: '', internalType: 'LeftRightUnsigned', type: 'uint256' },
      { name: '', internalType: 'LeftRightUnsigned', type: 'uint256' },
      { name: '', internalType: 'PositionBalance[]', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getCurrentTick',
    outputs: [{ name: 'currentTick', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getOracleTicks',
    outputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: 'spotTick', internalType: 'int24', type: 'int24' },
      { name: 'medianTick', internalType: 'int24', type: 'int24' },
      { name: 'latestTick', internalType: 'int24', type: 'int24' },
      { name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'builderCode', internalType: 'uint256', type: 'uint256' }],
    name: 'getRiskParameters',
    outputs: [
      {
        name: 'riskParameters',
        internalType: 'RiskParameters',
        type: 'uint256',
      },
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getTWAP',
    outputs: [{ name: 'twapTick', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'isSafeMode',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lockSafeMode',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes[]', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', internalType: 'bytes[]', type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'numberOfLegs',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'onERC1155Received',
    outputs: [{ name: '', internalType: 'bytes4', type: 'bytes4' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pokeOracle',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poolId',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poolKey',
    outputs: [{ name: 'key', internalType: 'bytes', type: 'bytes' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poolManager',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'TokenId', type: 'uint256' },
    ],
    name: 'positionData',
    outputs: [
      { name: '', internalType: 'bool', type: 'bool' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'int24', type: 'int24' },
      { name: '', internalType: 'int256', type: 'int256' },
      { name: '', internalType: 'int256', type: 'int256' },
      { name: '', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'reentrancyGuardEntered',
    outputs: [{ name: 'entered', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'riskEngine',
    outputs: [{ name: '', internalType: 'contract IRiskEngine', type: 'address' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unlockSafeMode',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      { name: 'usePremiaAsCollateral', internalType: 'bool', type: 'bool' },
    ],
    name: 'validateCollateralWithdrawable',
    outputs: [],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'liquidator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'liquidatee',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'bonusAmounts',
        internalType: 'LeftRightSigned',
        type: 'int256',
        indexed: false,
      },
    ],
    name: 'AccountLiquidated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'exercisor',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'exerciseFee',
        internalType: 'LeftRightSigned',
        type: 'int256',
        indexed: false,
      },
    ],
    name: 'ForcedExercised',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'recipient',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'positionSize',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'premiaByLeg',
        internalType: 'LeftRightSigned[4]',
        type: 'int256[4]',
        indexed: false,
      },
    ],
    name: 'OptionBurnt',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'recipient',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'balanceData',
        internalType: 'PositionBalance',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'OptionMinted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'legIndex',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'settledAmounts',
        internalType: 'LeftRightSigned',
        type: 'int256',
        indexed: false,
      },
    ],
    name: 'PremiumSettled',
  },
  {
    type: 'error',
    inputs: [
      { name: 'solvent', internalType: 'uint256', type: 'uint256' },
      { name: 'numberOfTicks', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'AccountInsolvent',
  },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'CastingError' },
  { type: 'error', inputs: [], name: 'DuplicateTokenId' },
  { type: 'error', inputs: [], name: 'EffectiveLiquidityAboveThreshold' },
  { type: 'error', inputs: [], name: 'InputListFail' },
  { type: 'error', inputs: [], name: 'InvalidTick' },
  { type: 'error', inputs: [], name: 'LiquidityTooHigh' },
  { type: 'error', inputs: [], name: 'NetLiquidityZero' },
  { type: 'error', inputs: [], name: 'NoLegsExercisable' },
  { type: 'error', inputs: [], name: 'NotGuardian' },
  { type: 'error', inputs: [], name: 'NotMarginCalled' },
  { type: 'error', inputs: [], name: 'PositionNotOwned' },
  { type: 'error', inputs: [], name: 'PriceImpactTooLarge' },
  { type: 'error', inputs: [], name: 'Reentrancy' },
  { type: 'error', inputs: [], name: 'StaleOracle' },
  { type: 'error', inputs: [], name: 'TokenIdHasZeroLegs' },
  { type: 'error', inputs: [], name: 'TooManyLegsOpen' },
  { type: 'error', inputs: [], name: 'UnderOverFlow' },
  { type: 'error', inputs: [], name: 'WrongPoolId' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// RiskEngine
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const riskEngineAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_crossBuffer0', internalType: 'uint256', type: 'uint256' },
      { name: '_crossBuffer1', internalType: 'uint256', type: 'uint256' },
      { name: '_guardian', internalType: 'address', type: 'address' },
      { name: '_builderFactory', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'ADJUSTMENT_SPEED',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'BP_DECREASE_BUFFER',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'BUILDER_SPLIT',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'BUYER_COLLATERAL_RATIO',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'CROSS_BUFFER_0',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'CROSS_BUFFER_1',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'CURVE_STEEPNESS',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DECIMALS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'EMA_PERIODS',
    outputs: [{ name: '', internalType: 'uint96', type: 'uint96' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'FORCE_EXERCISE_COST',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'INITIAL_RATE_AT_TARGET',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'IRM_MAX_ELAPSED_TIME',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAINT_MARGIN_RATE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_CLAMP_DELTA',
    outputs: [{ name: '', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_OPEN_LEGS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_RATE_AT_TARGET',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_SPREAD',
    outputs: [{ name: '', internalType: 'uint24', type: 'uint24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TICKS_DELTA',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TWAP_DELTA_DISPATCH',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_RATE_AT_TARGET',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'NOTIONAL_FEE',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'PREMIUM_FEE',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'PROTOCOL_SPLIT',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'SATURATED_POOL_UTIL',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'SELLER_COLLATERAL_RATIO',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TARGET_POOL_UTIL',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TARGET_UTILIZATION',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'VEGOID',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'recipient', internalType: 'address', type: 'address' },
    ],
    name: 'collect',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'recipient', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'collect',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' },
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
    ],
    name: 'computeInternalMedian',
    outputs: [
      { name: 'medianTick', internalType: 'int24', type: 'int24' },
      {
        name: 'updatedOraclePack',
        internalType: 'OraclePack',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'utilization', internalType: 'int256', type: 'int256' },
      { name: 'crossBuffer', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'crossBufferRatio',
    outputs: [{ name: 'crossBufferRatio', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: 'oracleTick', internalType: 'int24', type: 'int24' },
      { name: 'tokenId', internalType: 'TokenId', type: 'uint256' },
      {
        name: 'positionBalance',
        internalType: 'PositionBalance',
        type: 'uint256',
      },
    ],
    name: 'exerciseCost',
    outputs: [{ name: 'exerciseFees', internalType: 'LeftRightSigned', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'builderCode', internalType: 'uint256', type: 'uint256' }],
    name: 'getFeeRecipient',
    outputs: [{ name: 'feeRecipient', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'tokenData0',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'tokenData1',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      { name: 'atSqrtPriceX96', internalType: 'uint160', type: 'uint160' },
      { name: 'netPaid', internalType: 'LeftRightSigned', type: 'int256' },
      {
        name: 'shortPremium',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
    ],
    name: 'getLiquidationBonus',
    outputs: [
      { name: '', internalType: 'LeftRightSigned', type: 'int256' },
      { name: '', internalType: 'LeftRightSigned', type: 'int256' },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'positionBalanceArray',
        internalType: 'PositionBalance[]',
        type: 'uint256[]',
      },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      {
        name: 'shortPremia',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'longPremia',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'ct0',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
      {
        name: 'ct1',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
    ],
    name: 'getMargin',
    outputs: [
      {
        name: 'tokenData0',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'tokenData1',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'globalUtilizations',
        internalType: 'PositionBalance',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: '_oraclePack', internalType: 'OraclePack', type: 'uint256' },
    ],
    name: 'getOracleTicks',
    outputs: [
      { name: 'spotTick', internalType: 'int24', type: 'int24' },
      { name: 'medianTick', internalType: 'int24', type: 'int24' },
      { name: 'latestTick', internalType: 'int24', type: 'int24' },
      { name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'payor', internalType: 'address', type: 'address' },
      { name: 'fees', internalType: 'LeftRightSigned', type: 'int256' },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      {
        name: 'ct0',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
      {
        name: 'ct1',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
    ],
    name: 'getRefundAmounts',
    outputs: [{ name: '', internalType: 'LeftRightSigned', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' },
      { name: 'builderCode', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getRiskParameters',
    outputs: [{ name: '', internalType: 'RiskParameters', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: '_oraclePack', internalType: 'OraclePack', type: 'uint256' },
      { name: 'safeMode', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'getSolvencyTicks',
    outputs: [
      { name: '', internalType: 'int24[]', type: 'int24[]' },
      { name: '', internalType: 'OraclePack', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'guardian',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'liquidatee', internalType: 'address', type: 'address' },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      {
        name: 'premiasByLeg',
        internalType: 'LeftRightSigned[4][]',
        type: 'int256[4][]',
      },
      {
        name: 'collateralRemaining',
        internalType: 'LeftRightSigned',
        type: 'int256',
      },
      { name: 'atSqrtPriceX96', internalType: 'uint160', type: 'uint160' },
    ],
    name: 'haircutPremia',
    outputs: [
      { name: 'bonusDeltas', internalType: 'LeftRightSigned', type: 'int256' },
      {
        name: 'haircutTotal',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'haircutPerLeg',
        internalType: 'LeftRightSigned[4][]',
        type: 'int256[4][]',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'utilization', internalType: 'uint256', type: 'uint256' },
      {
        name: 'interestRateAccumulator',
        internalType: 'MarketState',
        type: 'uint256',
      },
    ],
    name: 'interestRate',
    outputs: [{ name: '', internalType: 'uint128', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'positionBalanceArray',
        internalType: 'PositionBalance[]',
        type: 'uint256[]',
      },
      { name: 'positionIdList', internalType: 'TokenId[]', type: 'uint256[]' },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      { name: 'user', internalType: 'address', type: 'address' },
      {
        name: 'shortPremia',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'longPremia',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
      {
        name: 'ct0',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
      {
        name: 'ct1',
        internalType: 'contract CollateralTracker',
        type: 'address',
      },
      { name: 'buffer', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'isAccountSolvent',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'currentTick', internalType: 'int24', type: 'int24' },
      { name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' },
    ],
    name: 'isSafeMode',
    outputs: [{ name: 'safeMode', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'pool', internalType: 'contract PanopticPool', type: 'address' }],
    name: 'lockPool',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'oraclePack', internalType: 'OraclePack', type: 'uint256' }],
    name: 'twapEMA',
    outputs: [{ name: '', internalType: 'int24', type: 'int24' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'pool', internalType: 'contract PanopticPool', type: 'address' }],
    name: 'unlockPool',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'utilization', internalType: 'uint256', type: 'uint256' },
      {
        name: 'interestRateAccumulator',
        internalType: 'MarketState',
        type: 'uint256',
      },
    ],
    name: 'updateInterestRate',
    outputs: [
      { name: '', internalType: 'uint128', type: 'uint128' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'vegoid',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'collateralToken',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'avgBorrowRate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'rateAtTarget',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BorrowRateUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'lockMode', internalType: 'bool', type: 'bool', indexed: false }],
    name: 'GuardianSafeModeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'recipient',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'TokensCollected',
  },
  { type: 'error', inputs: [], name: 'BelowMinimumRedemption' },
  { type: 'error', inputs: [], name: 'CastingError' },
  { type: 'error', inputs: [], name: 'InvalidBuilderCode' },
  { type: 'error', inputs: [], name: 'InvalidTick' },
  { type: 'error', inputs: [], name: 'LengthMismatch' },
  { type: 'error', inputs: [], name: 'LiquidityTooHigh' },
  { type: 'error', inputs: [], name: 'NotGuardian' },
  {
    type: 'error',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'balance', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'TransferFailed',
  },
  { type: 'error', inputs: [], name: 'UnderOverFlow' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SemiFungiblePositionManager
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const semiFungiblePositionManagerAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'poolManager',
        internalType: 'contract IPoolManager',
        type: 'address',
      },
      {
        name: '_minEnforcedTickFillCost',
        internalType: 'uint256',
        type: 'uint256',
      },
      {
        name: '_nativeEnforcedTickFillCost',
        internalType: 'uint256',
        type: 'uint256',
      },
      {
        name: '_supplyMultiplierTickFill',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'balanceOf',
    outputs: [{ name: 'balance', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owners', internalType: 'address[]', type: 'address[]' },
      { name: 'ids', internalType: 'uint256[]', type: 'uint256[]' },
    ],
    name: 'balanceOfBatch',
    outputs: [{ name: 'balances', internalType: 'uint256[]', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'poolKey', internalType: 'bytes', type: 'bytes' },
      { name: 'tokenId', internalType: 'TokenId', type: 'uint256' },
      { name: 'positionSize', internalType: 'uint128', type: 'uint128' },
      { name: 'tickLimitLow', internalType: 'int24', type: 'int24' },
      { name: 'tickLimitHigh', internalType: 'int24', type: 'int24' },
    ],
    name: 'burnTokenizedPosition',
    outputs: [
      { name: '', internalType: 'LeftRightUnsigned[4]', type: 'uint256[4]' },
      { name: '', internalType: 'LeftRightSigned', type: 'int256' },
      { name: '', internalType: 'int24', type: 'int24' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'poolId', internalType: 'uint64', type: 'uint64' }],
    name: 'expandEnforcedTickRange',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'poolKey', internalType: 'bytes', type: 'bytes' },
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'tokenType', internalType: 'uint256', type: 'uint256' },
      { name: 'tickLower', internalType: 'int24', type: 'int24' },
      { name: 'tickUpper', internalType: 'int24', type: 'int24' },
    ],
    name: 'getAccountLiquidity',
    outputs: [
      {
        name: 'accountLiquidities',
        internalType: 'LeftRightUnsigned',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'poolKey', internalType: 'bytes', type: 'bytes' },
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'tokenType', internalType: 'uint256', type: 'uint256' },
      { name: 'tickLower', internalType: 'int24', type: 'int24' },
      { name: 'tickUpper', internalType: 'int24', type: 'int24' },
      { name: 'atTick', internalType: 'int24', type: 'int24' },
      { name: 'isLong', internalType: 'uint256', type: 'uint256' },
      { name: 'vegoid', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getAccountPremium',
    outputs: [
      { name: '', internalType: 'uint128', type: 'uint128' },
      { name: '', internalType: 'uint128', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'poolKey', internalType: 'bytes', type: 'bytes' }],
    name: 'getCurrentTick',
    outputs: [{ name: 'currentTick', internalType: 'int24', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'poolId', internalType: 'uint64', type: 'uint64' }],
    name: 'getEnforcedTickLimits',
    outputs: [
      { name: '', internalType: 'int24', type: 'int24' },
      { name: '', internalType: 'int24', type: 'int24' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'bytes', type: 'bytes' },
      { name: 'vegoid', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'getPoolId',
    outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'poolId', internalType: 'uint64', type: 'uint64' }],
    name: 'getUniswapV4PoolKeyFromId',
    outputs: [
      {
        name: '',
        internalType: 'struct PoolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', internalType: 'Currency', type: 'address' },
          { name: 'currency1', internalType: 'Currency', type: 'address' },
          { name: 'fee', internalType: 'uint24', type: 'uint24' },
          { name: 'tickSpacing', internalType: 'int24', type: 'int24' },
          { name: 'hooks', internalType: 'contract IHooks', type: 'address' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'key',
        internalType: 'struct PoolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', internalType: 'Currency', type: 'address' },
          { name: 'currency1', internalType: 'Currency', type: 'address' },
          { name: 'fee', internalType: 'uint24', type: 'uint24' },
          { name: 'tickSpacing', internalType: 'int24', type: 'int24' },
          { name: 'hooks', internalType: 'contract IHooks', type: 'address' },
        ],
      },
      { name: 'vegoid', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'initializeAMMPool',
    outputs: [{ name: 'poolId', internalType: 'uint64', type: 'uint64' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'operator', internalType: 'address', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ name: 'approvedForAll', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'poolKey', internalType: 'bytes', type: 'bytes' },
      { name: 'tokenId', internalType: 'TokenId', type: 'uint256' },
      { name: 'positionSize', internalType: 'uint128', type: 'uint128' },
      { name: 'tickLimitLow', internalType: 'int24', type: 'int24' },
      { name: 'tickLimitHigh', internalType: 'int24', type: 'int24' },
    ],
    name: 'mintTokenizedPosition',
    outputs: [
      { name: '', internalType: 'LeftRightUnsigned[4]', type: 'uint256[4]' },
      { name: '', internalType: 'LeftRightSigned', type: 'int256' },
      { name: '', internalType: 'int24', type: 'int24' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes[]', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ name: 'results', internalType: 'bytes[]', type: 'bytes[]' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'reentrancyGuardEntered',
    outputs: [{ name: 'entered', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeBatchTransferFrom',
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address' },
      { name: 'approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'data', internalType: 'bytes', type: 'bytes' }],
    name: 'unlockCallback',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'idV4', internalType: 'PoolId', type: 'bytes32', indexed: true },
      {
        name: 'minEnforcedTick',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
      {
        name: 'maxEnforcedTick',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
    ],
    name: 'EnforcedTicksUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'poolId',
        internalType: 'PoolId',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenType',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'tickLower',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
      {
        name: 'tickUpper',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
      {
        name: 'liquidityDelta',
        internalType: 'int128',
        type: 'int128',
        indexed: false,
      },
    ],
    name: 'LiquidityChunkUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'idV4', internalType: 'PoolId', type: 'bytes32', indexed: true },
      {
        name: 'poolId',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: 'minEnforcedTick',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
      {
        name: 'maxEnforcedTick',
        internalType: 'int24',
        type: 'int24',
        indexed: false,
      },
    ],
    name: 'PoolInitialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'recipient',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'positionSize',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'TokenizedPositionBurnt',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'caller',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'TokenId',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'positionSize',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'TokenizedPositionMinted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'ids',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false,
      },
      {
        name: 'amounts',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false,
      },
    ],
    name: 'TransferBatch',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: false },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'TransferSingle',
  },
  { type: 'error', inputs: [], name: 'ChunkHasZeroLiquidity' },
  { type: 'error', inputs: [], name: 'InvalidTick' },
  { type: 'error', inputs: [], name: 'InvalidTickBound' },
  {
    type: 'error',
    inputs: [{ name: 'parameterType', internalType: 'uint256', type: 'uint256' }],
    name: 'InvalidTokenIdParameter',
  },
  { type: 'error', inputs: [], name: 'LiquidityTooHigh' },
  { type: 'error', inputs: [], name: 'NotAuthorized' },
  { type: 'error', inputs: [], name: 'NotEnoughLiquidityInChunk' },
  { type: 'error', inputs: [], name: 'PoolNotInitialized' },
  { type: 'error', inputs: [], name: 'PositionTooLarge' },
  {
    type: 'error',
    inputs: [{ name: 'currentTick', internalType: 'int24', type: 'int24' }],
    name: 'PriceBoundFail',
  },
  { type: 'error', inputs: [], name: 'Reentrancy' },
  { type: 'error', inputs: [], name: 'UnauthorizedUniswapCallback' },
  { type: 'error', inputs: [], name: 'UnderOverFlow' },
  { type: 'error', inputs: [], name: 'UnsafeRecipient' },
  { type: 'error', inputs: [], name: 'WrongUniswapPool' },
] as const
