export const SemiFungiblePositionManagerV1_1Abi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'poolManager', type: 'address', internalType: 'contract IPoolManager' },
      { name: '_minEnforcedTickFillCost', type: 'uint256', internalType: 'uint256' },
      { name: '_nativeEnforcedTickFillCost', type: 'uint256', internalType: 'uint256' },
      { name: '_supplyMultiplierTickFill', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [
      { name: 'account', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'balance', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOfBatch',
    inputs: [
      { name: 'owners', type: 'address[]', internalType: 'address[]' },
      { name: 'ids', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [{ name: 'balances', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'burnTokenizedPosition',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'tokenId', type: 'uint256', internalType: 'TokenId' },
      { name: 'positionSize', type: 'uint128', internalType: 'uint128' },
      { name: 'slippageTickLimitLow', type: 'int24', internalType: 'int24' },
      { name: 'slippageTickLimitHigh', type: 'int24', internalType: 'int24' },
    ],
    outputs: [
      { name: '', type: 'uint256[4]', internalType: 'LeftRightUnsigned[4]' },
      { name: '', type: 'int256', internalType: 'LeftRightSigned' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'expandEnforcedTickRange',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getAccountLiquidity',
    inputs: [
      { name: 'idV4', type: 'bytes32', internalType: 'PoolId' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'tokenType', type: 'uint256', internalType: 'uint256' },
      { name: 'tickLower', type: 'int24', internalType: 'int24' },
      { name: 'tickUpper', type: 'int24', internalType: 'int24' },
    ],
    outputs: [{ name: 'accountLiquidities', type: 'uint256', internalType: 'LeftRightUnsigned' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAccountPremium',
    inputs: [
      { name: 'idV4', type: 'bytes32', internalType: 'PoolId' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'tokenType', type: 'uint256', internalType: 'uint256' },
      { name: 'tickLower', type: 'int24', internalType: 'int24' },
      { name: 'tickUpper', type: 'int24', internalType: 'int24' },
      { name: 'atTick', type: 'int24', internalType: 'int24' },
      { name: 'isLong', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: '', type: 'uint128', internalType: 'uint128' },
      { name: '', type: 'uint128', internalType: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getEnforcedTickLimits',
    inputs: [{ name: 'idV4', type: 'bytes32', internalType: 'PoolId' }],
    outputs: [
      { name: '', type: 'int24', internalType: 'int24' },
      { name: '', type: 'int24', internalType: 'int24' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolId',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolId',
    inputs: [{ name: 'idV4', type: 'bytes32', internalType: 'PoolId' }],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUniswapV4PoolKeyFromId',
    inputs: [{ name: 'poolId', type: 'uint64', internalType: 'uint64' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initializeAMMPool',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isApprovedForAll',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'operator', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'approvedForAll', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mintTokenizedPosition',
    inputs: [
      {
        name: 'key',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'tokenId', type: 'uint256', internalType: 'TokenId' },
      { name: 'positionSize', type: 'uint128', internalType: 'uint128' },
      { name: 'slippageTickLimitLow', type: 'int24', internalType: 'int24' },
      { name: 'slippageTickLimitHigh', type: 'int24', internalType: 'int24' },
    ],
    outputs: [
      { name: '', type: 'uint256[4]', internalType: 'LeftRightUnsigned[4]' },
      { name: '', type: 'int256', internalType: 'LeftRightSigned' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'safeBatchTransferFrom',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'safeTransferFrom',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'setApprovalForAll',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'unlockCallback',
    inputs: [{ name: 'data', type: 'bytes', internalType: 'bytes' }],
    outputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'ApprovalForAll',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'approved', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EnforcedTicksUpdated',
    inputs: [
      { name: 'idV4', type: 'bytes32', indexed: true, internalType: 'PoolId' },
      { name: 'minEnforcedTick', type: 'int24', indexed: false, internalType: 'int24' },
      { name: 'maxEnforcedTick', type: 'int24', indexed: false, internalType: 'int24' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PoolInitialized',
    inputs: [
      { name: 'idV4', type: 'bytes32', indexed: true, internalType: 'PoolId' },
      { name: 'poolId', type: 'uint64', indexed: false, internalType: 'uint64' },
      { name: 'minEnforcedTick', type: 'int24', indexed: false, internalType: 'int24' },
      { name: 'maxEnforcedTick', type: 'int24', indexed: false, internalType: 'int24' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenizedPositionBurnt',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      { name: 'positionSize', type: 'uint128', indexed: false, internalType: 'uint128' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenizedPositionMinted',
    inputs: [
      { name: 'caller', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'TokenId' },
      { name: 'positionSize', type: 'uint128', indexed: false, internalType: 'uint128' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferBatch',
    inputs: [
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'ids', type: 'uint256[]', indexed: false, internalType: 'uint256[]' },
      { name: 'amounts', type: 'uint256[]', indexed: false, internalType: 'uint256[]' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferSingle',
    inputs: [
      { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'from', type: 'address', indexed: true, internalType: 'address' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'CastingError', inputs: [] },
  { type: 'error', name: 'InvalidTick', inputs: [] },
  { type: 'error', name: 'InvalidTickBound', inputs: [] },
  {
    type: 'error',
    name: 'InvalidTokenIdParameter',
    inputs: [{ name: 'parameterType', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'NotAuthorized', inputs: [] },
  { type: 'error', name: 'NotEnoughLiquidity', inputs: [] },
  { type: 'error', name: 'PoolNotInitialized', inputs: [] },
  { type: 'error', name: 'PositionTooLarge', inputs: [] },
  { type: 'error', name: 'PriceBoundFail', inputs: [] },
  { type: 'error', name: 'UnauthorizedUniswapCallback', inputs: [] },
  { type: 'error', name: 'UnderOverFlow', inputs: [] },
  { type: 'error', name: 'UniswapPoolNotInitialized', inputs: [] },
  { type: 'error', name: 'UnsafeRecipient', inputs: [] },
  { type: 'error', name: 'ZeroLiquidity', inputs: [] },
] as const
